### ISSUE TITLE
 Can't open file syntax/jade.vim

### ISSUE THREAD

**Issue by stephanedemotte** [posva/vim-vue#1]
Hi 

When i try to open a file.vue, i have this error : 
```
 Can't open file syntax/jade.vim
```

Any idea ?

Thanks !

**Comment by gconsidine** [comment]
@stephanedemotte I just started using Vue last night and encountered this same problem.  On the offhand chance that you haven't figured this out yet, it's failing because you're missing a syntax file for Jade which doesn't come with a default installation of vim.  In my case, I was missing CoffeScript and Stylus.

To fix the issue, install this plugin:

* **Jade** https://github.com/digitaltoad/vim-jade

Other possible culprits for people who stumble upon this same issue:

* **CoffeeScript** https://github.com/kchmck/vim-coffee-script
* **Stylus** https://github.com/wavded/vim-stylus

There's gotta be a way to use Vundle, pathogen, or w/e. to fetch these dependencies on install, but I don't have time to sort that out and open a PR on this project right now.

**Comment by posva** [comment]
@stephanedemotte God, I'm sorry, I wasn't watching my repo so I wasn't receiving any notifications...
As @gconsidine pointed it out, you're missing the some syntax files. I need to just disable the syntax highlight if the syntax is missing... That'd be easier.

**Comment by posva** [comment]
@gconsidine Thank you very much BTW. That was such a nice answer :smiley:

**Comment by stephanedemotte** [comment]
Thanks all :)
