### ISSUE TITLE
Vim Vue syntax doesn't work. 

### ISSUE THREAD

**Issue by asolopovas** [posva/vim-vue#10]
All other syntaxes are fine. Just in case here is the list of plugins I use

Plugin 'VundleVim/Vundle.vim'           " Package Manager

Plugin 'jwalton512/vim-blade'           " Blade Syntax Support
Plugin 'posva/vim-vue'                  " Vue Syntax Support
Plugin 'othree/html5.vim'               " Html5 Syntax Support

I php, js syntax work fine.

**Comment by asolopovas** [comment]
I think the issue is with file name starting from Capital Letter. With lowercase it works fine.

**Comment by posva** [comment]
Hello
If you're using `file.Vue` instead of `file.vue` then yeah, that's just that the filetype is not being detected. I don't think supporting uppercase extension is a good idea, so I'm closing the issue. If you want vim-vue to work with *.Vue files add `au BufNewFile,BufRead *.Vue setf vue` to your .vimrc
