### ISSUE TITLE
Getting errors when using custom tags

### ISSUE THREAD

**Issue by ricvillagrana** [posva/vim-vue#131]
I am getting lint errors when using custom tags check the screenshot below, I have installed eslint and everything in my vimrcis as README says.

<img width="1920" alt="screen shot 2019-02-26 at 10 21 52 pm" src="https://user-images.githubusercontent.com/9273142/53465894-536eb800-3a15-11e9-9754-fafa9c725644.png">

**Comment by adriaanzon** [comment]
I see you have set your `filetype` option to "vue.html.javascript.css". This causes your linting plugin to see the buffer as an HTML file, which in turn runs `tidy` over the file as if it were an html file.

The part in the readme about vue.html.javascript.css is not something we actually support, it just serves as a quick way to help existing plugins recognize the file. However, the mileage across different plugins may vary, hence the warning underneath it in de readme.

I think we're better of removing this tip from the readme, because it seems to do more harm than good.
